### ISSUE TITLE
Why am I getting these errors ?

### ISSUE THREAD

**Issue by Windspar** [BindBC/bindbc-freeimage#6]
freeimage/binddynamic.d(320,15): Error: undefined identifier `fiSupport`
, did you mean enum `FISupport`?

freeimage/binddynamic.d(583,15): Error: undefined identifier `fiSupport`
, did you mean enum `FISupport`?

Using fedora 36 with freeimage 3.19.

**Comment by mdparker** [comment]
You're seeing the errors because the compile-time configuration logic in types.d is wrong and doesn't have a default case. I'll fix it when I can, but for now you can add a `FI_317` version (or `FI_318` if you use anything specific from the FreeImage 3.18 API) to your dub config and that will solve the problem locally.

**Comment by mdparker** [comment]
I've pushed the fix as v1.0.2. The binding doesn't yet support the 3.19 API, so as long as you aren't using anything added in that version, everything should be good to go. I'll add 3.19 support soon.

**Comment by mdparker** [comment]
Hmm. Actually, I don't see any 3.19 releases here:

https://freeimage.sourceforge.io/download.html

**Comment by Windspar** [comment]
This is what fedora 36 has
freeimage.x86_64                                  3.19.0-0.10.svn1889.fc36               @updates                        
freeimage-devel.x86_64                            3.19.0-0.10.svn1889.fc36               @updates 

Thanks that solved it.
